resilience4j.retry:
  instances:
    externalService:
      max-attempts: 3        # Número de tentativas
      wait-duration: 2s      # Intervalo entre tentativas
      retry-exceptions:
        - org.springframework.web.client.ResourceAccessException
        - java.io.IOException

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/aviationdb
    username: aviation
    password: aviation123
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
