version: '3.8'
services:
  postgres:
    image: postgres:16
    container_name: aviation-postgres
    restart: always
    environment:
      POSTGRES_DB: aviationdb
      POSTGRES_USER: aviation
      POSTGRES_PASSWORD: aviation123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
